# Generated by Django 2.2.7 on 2019-11-12 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
