# Generated by Django 2.2.7 on 2019-11-12 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
