# Generated by Django 2.2.7 on 2019-11-12 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191112_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
